name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: serve files
        uses: Eun/http-server-action@v1
        with:
          directory: ${{ github.workspace }}
          port: 8888
      - uses: actions/checkout@v2
        with:
          repository: tatut/cypress-example-todomvc
          path: cypress-todomvc
      - name: run todomvc cypress tests
        run: bash cypress.sh
